### ISSUE TITLE
Index out of bounds exception on setter

### ISSUE THREAD

**Issue by jwaterloo** [minimalcode-org/minimalcode-beans#2] opened 2016-02-09 01:13 UTC
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:635)
        at java.util.ArrayList.get(ArrayList.java:411)
        at org.minimalcode.beans.ObjectWrapper.getIndexedValue(ObjectWrapper.java:602)
        at org.minimalcode.beans.ObjectWrapper.getValue(ObjectWrapper.java:549)
        at org.minimalcode.beans.ObjectWrapper.setValue(ObjectWrapper.java:690)
        at org.minimalcode.beans.ObjectWrapper.setValue(ObjectWrapper.java:303)
        at com.power_suite.database_migration.key_risk_management.IdempotentInsert.init(IdempotentInsert.java:334)
        at com.power_suite.database_migration.key_risk_management.IdempotentInsert.generateStatements(IdempotentInsert.java:172)
        at liquibase.change.custom.CustomChangeWrapper.generateStatements(CustomChangeWrapper.java:178)

...

import liquibase.change.core.LoadDataColumnConfig;

public class TargetClass {
  private List&lt;LoadDataColumnConfig&gt; columns = new ArrayList&lt;LoadDataColumnConfig&gt;();

  public List&lt;LoadDataColumnConfig&gt; getColumns() {
    return columns;
  }

  public void setColumns(List&lt;LoadDataColumnConfig&gt; columns) {
    this.columns = columns;
  }

  public void init() {
    ObjectWrapper wrapper = new ObjectWrapper(this);
    // failing expression
    wrapper.setValue("columns[0].header", "PRFL_STMT_ID");
  }
}

**Comment by dewos** [comment] 2016-05-17 22:16
Hi @jwaterloo, Can you reformat this, please? It's very chaotic.

**Comment by jwaterloo** [comment] 2016-05-19 01:05
I don't know how to format it better. Any suggestions. Whatever formatting it received was involuntary by github. The first half is the stack trace of the exception. The second half is the code, a single class declaration. The 2nd class that I did not paste in for simplicity, LoadDataColumnConfig, just have a single property, header, as described in the path. ... I try to add 2 separate comments following this one to separate the exception from the class definition to see if that helps the formatting any.

**Comment by jwaterloo** [comment] 2016-05-19 01:05
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:635)
        at java.util.ArrayList.get(ArrayList.java:411)
        at org.minimalcode.beans.ObjectWrapper.getIndexedValue(ObjectWrapper.java:602)
        at org.minimalcode.beans.ObjectWrapper.getValue(ObjectWrapper.java:549)
        at org.minimalcode.beans.ObjectWrapper.setValue(ObjectWrapper.java:690)
        at org.minimalcode.beans.ObjectWrapper.setValue(ObjectWrapper.java:303)
        at com.power_suite.database_migration.key_risk_management.IdempotentInsert.init(IdempotentInsert.java:334)
        at com.power_suite.database_migration.key_risk_management.IdempotentInsert.generateStatements(IdempotentInsert.java:172)
        at liquibase.change.custom.CustomChangeWrapper.generateStatements(CustomChangeWrapper.java:178)

**Comment by jwaterloo** [comment] 2016-05-19 01:06
import liquibase.change.core.LoadDataColumnConfig;

public class TargetClass {
  private List&lt;LoadDataColumnConfig&gt; columns = new ArrayList&lt;LoadDataColumnConfig&gt;();

  public List&lt;LoadDataColumnConfig&gt; getColumns() {
    return columns;
  }

  public void setColumns(List&lt;LoadDataColumnConfig&gt; columns) {
    this.columns = columns;
  }

  public void init() {
    ObjectWrapper wrapper = new ObjectWrapper(this);
    // failing expression
    wrapper.setValue("columns[0].header", "PRFL_STMT_ID");
  }
}

**Comment by dewos** [comment] 2016-05-19 07:25
@jwaterloo It seems to me that your **List columns** is an empty ArrayList without the JAVA GENERICS: the ObjectWrapper cannot know what to put iin [0]. so the Exception. No issue here. Try with the java generics (`List<Something>`) or do:

``` java
ObjectWrapper wrapper = new ObjectWrapper(this);
wrapper.setValue("columns[0]", new Something());
wrapper.setValue("columns[0].header",  "PRFL_STMT_ID");
```

**Comment by jwaterloo** [comment] 2016-05-20 02:18
The collection and property was generic, github formatting is hidding that fact. I have replaced the less than and greater than with the xml encoding manually. In any case it is generic and with your autoinstancing feature, it should have created it.

**Comment by dewos** [comment] 2016-05-20 05:28
Reopened :+1: Ok, I'll test this out in the weekend. I'll let you know when I get more info.

**Comment by dewos** [comment] 2016-07-01 20:43
duplicate of #4

**Closed as completed by dewos** 2016-07-01 20:43 UTC
Labels: enhancement
